/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNISugar */

#ifndef _Included_JNISugar
#define _Included_JNISugar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNISugar
 * Method:    Start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNISugar_Start
  (JNIEnv *, jobject);

/*
 * Class:     JNISugar
 * Method:    Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNISugar_Stop
  (JNIEnv *, jobject);

/*
 * Class:     JNISugar
 * Method:    Wait
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNISugar_Wait
  (JNIEnv *, jobject);

/*
 * Class:     JNISugar
 * Method:    CreateUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNISugar_CreateUser
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     JNISugar
 * Method:    CreateAdmin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNISugar_CreateAdmin
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
